backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://maine-weather-report.netlify.com
display_url: https://maine-weather-report.netlify.com
show_preview_links: true

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_library:
  name: uploadcare
  config:
    publicKey: ac78278cad46e4c5e923
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    card: {type: "alltype", text: "title"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Dek", name: "dek", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
